### ISSUE TITLE
Vertnet API

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#10]
There seems to be a new web interface (http://portal.vertnet.org/) for Vernet - but I don't see anything about a new API. Anybody know what's going on with Vetnet's API? 

Most of the old function call examples work, but it seems odd that there is no way to get data on mammals given that its vertebrate data, especially given that you can get mammal data on their new web interface.

**Comment by Pika8tona** [comment]
Updated to work with new API.
