### ISSUE TITLE
Where is bigsearch function

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#16]
hi @Pika8tona - I don't see the `bigsearch()` function anywhere. Is it in your local branch on your computer, and didn't make it up here somehow?  There is a `.Rd` file for it, but no function definition for it.

**Comment by sckott** [comment]
this causes a problem on attempting to install:

```r
install()
```

```r
Installing rvertnet
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/Users/sacmac/github/ropensci/rvertnet' --library='/Users/sacmac/Library/R/3.1/library'  \
  --install-tests 

* installing *source* package ‘rvertnet’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : undefined exports: bigsearch
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/sacmac/Library/R/3.1/library/rvertnet’
* restoring previous ‘/Users/sacmac/Library/R/3.1/library/rvertnet’
Error: Command failed (1)
```

**Comment by Pika8tona** [comment]
Looks like there was a conflict that I didn't solve correctly.  I see R/bigsearch marked all in red...

Chris Ray
University of Colorado-Boulder
cray@colorado.edu
303-459-0176 / 303-489-8863
________________________________________

**Comment by sckott** [comment]
in this commit, looks like you somehow deleted it https://github.com/ropensci/rvertnet/commit/0fce50f39293aa5635417fdaf39fa2ed5ac4ca0e and then pushed that change up here.

**Comment by Pika8tona** [comment]
bigsearch is deleted locally, too.  Sigh.  I have no idea how.  I'll recreate it from the deleted bit I see on github.

Chris Ray
University of Colorado-Boulder
cray@colorado.edu
303-459-0176 / 303-489-8863
________________________________________

**Comment by Pika8tona** [comment]
I think this issue is fixed.

**Comment by sckott** [comment]
great, thanks
