### ISSUE TITLE
Remove some files

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#17]
@Pika8tona 

Some files shouldn't be in the root directory of the package:

* vertnet-manual.pdf
* rvertnet_0.2.tar.gz

The manual will be created on build steps on CRAN when it gets to cran, but you can keep it therer for now. 

the tarball isn't needed as when people install from Github they can do install_github("ropensci/rvertnet") and its not needed there, and when its on cran, they create the appropriate tarballs for us. 

Add these two files to `.Rbuildignore` so that when we run check they aren't checked

**Comment by Pika8tona** [comment]
Added to .Rbuildignore

**Comment by Pika8tona** [comment]
Sorry, closed on accident.
