### ISSUE TITLE
binomial "species" vs specific epithet

### ISSUE THREAD

**Issue by Pika8tona** [ropensci/rvertnet#20]
In searchbyterm and bigsearch the user should be prompted for just the specific epithet ("leo" in "Panthera leo") when entering "species", because the "specificepithet" field in VertNet usually does not contain a binomial.  For example, when I search for sp="ochotona princeps" I get 78 results, compared to over 6800 results for genus="ochotona" combined with sp="princeps"

**Comment by sckott** [comment]
Okay, in your examples in the package you were passing binomials to the parameter `specificepithet` though so I thought that's what it was supposed to be  - it does make sense that `specificepithet`  should just be e.g., `sapiens` in `Homo sapiens`
