### ISSUE TITLE
Check that old version problems don't still exist

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#21]
from use email:

```r
vertoccurrence(grp='herp', t='Crotalus oreganus')
Error in textConnection(text, encoding = "UTF-8") :
invalid 'text' argument
```

`z <- vertoccurrence(grp='fish', t='Ventrifossa macropogon')`

In this instance, for whatever reason, the longitude and latitude columns are of class factor. This means that if you simply plot the occurrences, the coordinates are coerced directly from factor to numeric, resulting in nonsensical coordinates. Seems to me that perhaps these columns should at least be coerced to character prior to being returned by the function.

**Comment by Pika8tona** [comment]
I think any of the old fns that I didn't address via that "update" branch (before the merge), should be deleted from the package because they are redundant with new functions or not particularly compatible with the new API.

**Comment by sckott** [comment]
@Pika8tona good good, just gonna do a check against this type of problem just in case...
