### ISSUE TITLE
remove binomial from example

### ISSUE THREAD

**Issue by Pika8tona** [ropensci/rvertnet#22]
To keep folks from accidentally limiting their search results by entering a binomial instead of a specific epithet, these lines can be omitted from the headers in searchbyterm and bigsearch:
#' # Find records in multiple locations
#' out <- searchbyterm(specificepithet = "mustela nigripes")
#'
Looks like they were a holdover that I missed--sorry.

**Comment by sckott** [comment]
okay, sounds good
