### ISSUE TITLE
bigsearch should fail better

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#24]
* when given no inputs except email and file name, should fail (or does this request a dump of all of vertnet? if so, I think we'd want that to fail, no?) 
* rfile and email are required fields, should fail if not given

**Comment by Pika8tona** [comment]
I didn't test for that.

**Comment by sckott** [comment]
@Pika8tona no worries, just poking around writing tests, and these things popped out as being potential frustration points for users
