### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#25]
@Pika8tona Do you know if you have used the cursor functionality in `rvertnet`?  I don't see it anywhere in the package, but maybe you have used it. 

Or maybe `bigsearch()` is a replacement for paging over results to get more than 1000?

cc @dbloom any thoughts?

**Comment by Pika8tona** [comment]
@dbloom @sckott - right - because of the bigsearch() option I did not yet implement any use of the cursor for paging over results

**Comment by sckott** [comment]
should be done - will run tests and inspect further
