### ISSUE TITLE
Fix to allow certain parameters to handle multiple values

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#37]
e.g, `year`

**Comment by Pika8tona** [comment]
Nice!

Chris Ray
________________________________________

**Comment by sckott** [comment]
@Pika8tona are there others?  i think year is a weird one cause it can use `>=` type symbols, so we cant  do e..g, `> 1976 OR < 1979`

**Comment by Pika8tona** [comment]
That's the one I recall.

Chris Ray
________________________________________
