### ISSUE TITLE
bigsearch uses wrong mappable query

### ISSUE THREAD

**Issue by ptitle** [ropensci/rvertnet#46]
If I run the following code:
bigsearch(genus = 'Crotalus', mappable = TRUE, rfile = 'Crotalus_vertnet', email = 'myemail@myemail.edu')

... I quickly get an email with the resulting file, which has zero records.
But in the email, the query reads: "Query: genus:Crotalus mappable:true"

I believe it should be "mappable:1". 
I haven't checked to see if this is happening for all logical flags.

**Comment by vijaybarve** [comment]
@ptitle  You are right. The function call should be 
````
bigsearch(genus = 'Crotalus', mappable = 1, rfile = 'Crotalus_vertnet', email = 'myemail@myemail.edu')
````

**Comment by ptitle** [comment]
In that case, the documentation for the function should be adjusted, as it says mappable is logical, which most people would assume means TRUE or FALSE.

**Comment by sckott** [comment]
hmm, testing right now

**Comment by sckott** [comment]
looks like `mappable` works in `searchbyterm()` function, but I forgot to update the internal code in `bigsearch()` function. It makes more sense to have a user pass a logical, so internally in `searchbyterm()` we convert logical to 1/0. I'll implement that in `bigsearch()` and push up a new patch version soon. 

This also applies to the parameters `media` and `tissue`
