### ISSUE TITLE
externalptr error with CRAN version 0.2.2

### ISSUE THREAD

**Issue by djhocking** [ropensci/rvertnet#48]
I installed rvertnet from CRAN by habit rather than via github, so it installed version 0.2.2. This resulted in the documentation/vignettes online not matching, old functions, and a couple errors with functions. This might be irrelevant given the github version but it might be worth submitting a newer version to CRAN (or getting rid of the the CRAN version and just using GitHub). Feel free to close without comment if this is not useful.

```
install.packages("rvertnet")

Installing package into ‘/Users/Dan/Library/R/3.1/library’
(as ‘lib’ is unspecified)

  There is a binary version available (and will be installed) but the
  source version is later:
         binary source
rvertnet  0.2.2  0.4.1

library(rvertnet)
library(XML)
```
Error using `vertoccurrence`

```
>nvir <- vertoccurrence(t="Notophthalmus viridescens", grp="herp")
Error in textConnection(text, encoding = "UTF-8") : 
  invalid 'text' argument
```

Error using `vertsearch`:

```
> nvir <- vertsearch(taxon="Notophthalmus viridescens")
Error in vertsearch(taxon = "Notophthalmus viridescens") : 
  unused argument (taxon = "Notophthalmus viridescens")

> nvir <- vertsearch(sp="Notophthalmus viridescens")
Error in out$records : object of type 'externalptr' is not subsettable
```

Function `bigsearch` not available:
```
> ?bigsearch
No documentation for ‘bigsearch’ in specified packages and libraries:
you could try ‘??bigsearch’
```

**Comment by sckott** [comment]
thanks, so the examples above were run with `v0.2.2` ?

**Comment by sckott** [comment]
I'm guessing you are on an older mac osx version?

**Comment by sckott** [comment]
There's no way for me to make CRAN update the old binary version for mac snowleapord, wish there was. When `install.packages()` asks if you want source version, you can say yes so you get a more recent version

**Comment by djhocking** [comment]
Yeah it appears that I was running everything with version 0.2.2. I didn't realize before initially contacting you (sorry). I'm on el capitan (10.11.3) but my R version is 3.1.3. Anyway, things seem to be working now that I'm using the GitHub version. The only thing that doesn't is the limit > 1000 option. In the tutorial it says it can handle that but it accurately says in the documentation that the limit is still 1000 and piping will be added in the future.

**Comment by sckott** [comment]
Glad it works. 

Hmm, i need to update the docs. You can get > 1000 now, see e.g., 

```r
out <- searchbyterm(class = "aves", limit = 1200)
NROW(out$data)
#> [1] 1200
```

**Comment by sckott** [comment]
though another option for large datasets is the `bigsearch()` function, which emails you a file after processing

**Comment by djhocking** [comment]
Yeah, I was using `bigsearch()` after trying `limit = 3000` in the `vertsearch()` function. I will try the `searchbyterm()` now since it's easier for something like this without too many records. Thanks again!

**Comment by djhocking** [comment]
Strange the `searchbyterm()` didn't allow me to go beyond 1000.

```
> nvir_nc <- searchbyterm(genus="Notophthalmus", stateprovince = "north carolina", limit = 3000)
Processing request...

Last Query URL: "http://api.vertnet-portal.appspot.com/api/search?q=%7B%22q%22%3A%22genus%3ANotophthalmus%20stateprovince%3Anorth%20carolina%22%2C%22l%22%3A3000%7D"

Matching records: 1000 returned, 2222 available
> nrow(nvir_nc$data)
[1] 1000
```
This is with version `rvertnet_0.4.1.9400` from GitHub.

**Comment by sckott** [comment]
okay, I'll have a look, not sure why that doesn't work

**Comment by djhocking** [comment]
FYI, your use of 

```
out <- searchbyterm(class = "aves", limit = 1200)
NROW(out$data)
```

Did produce the same result on my machine with 1200 records.

**Comment by sckott** [comment]
oh good

**Comment by sckott** [comment]
okay, reinstall from github `devtools::install_github("ropensci/rvertnet")` and your eg. try again

**Comment by sckott** [comment]
let me know if it works now @djhocking

**Comment by djhocking** [comment]
Sorry it took me a while to get back to this. It works like a charm. Thanks again!

**Comment by sckott** [comment]
great, thanks
