### ISSUE TITLE
incorporate trait data into package

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#55]
docs: https://github.com/VertNet/webapp/wiki/The-API-search-function#trait 

-----

e.g.'s

http://portal.vertnet.org/search?q=genus:Ochotona+hasmass:1+haslength:1 
   
generates a list of all pikas that have mass and length measurements. 

http://portal.vertnet.org/search?q=genus:Ochotona+lengthinmm+%3E=+100+lengthinmm+%3C=+1000+lengthtype:total+length+hasmass:1+haslength:1

generates the same list with those specimens between 100mm and 1000mm in length.

**Comment by sckott** [comment]
to try reinstall from github `devtools::install_github("ropensci/rvertnet")`

and see function `?traitsearch`

**Comment by robgur** [comment]
excited!  Trying now

**Comment by dbloom** [comment]
Awesome!  Let me know how it goes and we'll update our web site and post to
the blogosphere too.

**Comment by sckott** [comment]
- [ ] write tests for fxn
- [ ] add note/egs to other fxns on how to include trait queries

**Comment by robgur** [comment]
Should we make a little announcement about this, if we think we are good
here?

**Comment by sckott** [comment]
sure, i think we're good now. need to sort out #56 before next version to cran just fyi
