### ISSUE TITLE
dumps: new trait dataset, and possibly new URLs?

### ISSUE THREAD

**Issue by sckott** [ropensci/rvertnet#56]
http://datacommons.cyverse.org/browse/iplant/home/shared/commons_repo/curated/VertNet_Traits

http://blog.vertnet.org/post/151662714981/new-vertnet-taxon-based-snapshots-are-now

**Comment by dbloom** [comment]
New and old data sets are posted at
http://vertnet.org/resources/datatoolscode.html

**Comment by sckott** [comment]
@dbloom are there permalinks for the datasets that machines can download?  if not, i'll probably remove the functions that work with the bulk datasets.

**Comment by sckott** [comment]
> The files can be accessed directly by using the following form http://datacommons.cyverse.org/download/iplant/home/shared/commons_repo/curated/VertNet_Reptilia_Oct2015/VertNet_Reptilia_Oct2015.zip in place of the one with "browse" in the URL.

**Comment by sckott** [comment]
too complicated, now that dumps are csv would have to have user create sql table schema, etc. 

removing fxn
