### ISSUE TITLE
Same bigsearch returning different matching records number

### ISSUE THREAD

**Issue by Geiziane** [ropensci/rvertnet#70]
I did the following search two times:

bigsearch(class = "aves",country = "Brazil", rfile = "aves_vertnet", email = "myemail")

However, the e-mails received indicate different number of matching records:

1- Query: class:aves country:Brazil
Matching records: 80000
Request submitted: 2020-12-02T18:23:40.888366
Request fulfilled: 2020-12-02T22:43:57.506559

2- Query: class:aves country:Brazil
Matching records: 167701
Request submitted: 2020-12-02T16:53:38.789354
Request fulfilled: 2020-12-02T23:05:40.452602

**Comment by sckott** [comment]
Thanks @Geiziane for the report

@robgur @dbloom Any ideas? In theory there could have been some change in the database in that time between when those queries were fulfilled.

**Comment by Geiziane** [comment]
Hi @sckott the requests are less than two hour apart.

**Comment by sckott** [comment]
Right, I can see that. It's possible there was an error in counting the number of records reported to rvertnet. Did you get the emails for those two requests, and download the files? Did they match the records reported above?

**Comment by Geiziane** [comment]
Yes, I download them and they have the reported number.
See below the link for each query.

1- Query: class:aves country:Brazil
Matching records: 80000
https://storage.googleapis.com/vn-downloads2/aves_vertnet-24f99dc5b3974cdb883290102654b0dd.txt

2- Query: class:aves country:Brazil
Matching records: 167701
https://storage.googleapis.com/vn-downloads2/aves_vertnet-f159592a5c414431941af14fd4436ea7.txt

**Comment by robgur** [comment]
I sent this on to John W.  I hope we hear something back.

**Comment by sckott** [comment]
thanks much

**Comment by tucotuco** [comment]
Hi folks,

That first result with the nice round number 80000 looks suspiciously like there was a glitch in the csv file composer. Files are constructed from 10k record chunks and the composer puts them all together when the signal arrives that they are all done.  The glitch seems to be rare and unpredictable - the worst kind of thing to try to troubleshoot and fix. 

The second result is the correct one.

Sorry for the confusion and inconvenience,

John

**Comment by sckott** [comment]
Thanks John! Anything we can do on our side (i.e., this R client)? Or do we just document this to let users know it can happen?

**Comment by tucotuco** [comment]
There is no way the count can be known accurately until the results are
composed, so I don't think there is anything that can be done given the
back end.

**Comment by sckott** [comment]
Okay, thanks.

**Comment by sckott** [comment]
- [ ] Document known possibility that sometimes queries may contain "funky" results.

**Comment by maelle** [comment]
This repository is about to be archived.
